---
title: "Breast Cancer Detection"
author: "Rose Ellison"
date: "3/12/2021"
output:
  pdf_document: default
  html_document: default
---

# Breast Cancer Detection

## Set up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(caTools)
```


## Data Exploration
```{r}
# Read the data
data <- read.csv("./data/breast_cancer.csv")
```

## Attribute Information
1. Sample code number : id number
2. Clump Thickness : 1-10
3. Uniformity of Cell Size : 1-10
4. Uniformity of Cell Shape : 1-10
5. Marginal Adhesion : 1-10
6. Single Epithlial Cell Size : 1-10
7. Bare Nuclei : 1-10
8. Bland Chromatin : 1-10
9. Normal Nucleoli : 1-10
10. Mitoses : 1-10
11. Class (2 for benign, 4 for malignant)

## Cleaning the data
```{r}
sum(is.na(data)) # No missing values
data$Class <- ifelse(data$Class == 4, 1, 0)
```


```{r}
# Splitting the data
set.seed(1)
split <- sample.split(data$Class, SplitRatio = .8)
training <- subset(data, split == TRUE)
test <- subset(data, split == FALSE)




# Fitting Logistic Regression to the training set
classifier <- glm(Class ~ . , 
                  family = binomial,
                  data = data)


summary(classifier)

# Predicting the test set results
prob_pred <- predict(classifier, 
                     type = 'response', 
                     newdata = test[-11])

y_pred <- ifelse(prob_pred > 0.5, 1, 0)

# Making the Confusion Matrix
cm <- table(test[ , 11], y_pred)


# Model Accuracy
model_accuracy <- (cm[1,1] + cm[2,2]) / (cm[1,1] + cm[1,2] + cm[2,1] + cm[2,2])
paste("Assuming 50% probability as cutoff, model accuracy is ", model_accuracy)

```

